name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Build
      run: swift build -v
